name: flutter_powerauth_mobile_sdk_plugin
description: "Flutter Mobile SDK for PowerAuth Protocol (iOS, Android)."
version: 1.1.0
homepage: https://www.wultra.com/products/mobile-first-authentication

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wultra.android.powerauth.flutter
        pluginClass: PowerAuthPlugin
      ios:
        pluginClass: PowerAuthPlugin
