name: "Build iOS"

on:
  pull_request:
    branches:
      - develop

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install Flutter
        run: brew install --cask flutter
      - name: Get Flutter Dependencies
        run: pushd example && flutter pub get && popd
      - name: Install Pods
        run: pod install --project-directory=example/ios
      - name: Build iOS App
        run: pushd example && flutter build ios --release --no-codesign --no-tree-shake-icons && popd
