name: "Build Android"

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:

jobs:
  build-android:
    name: Build Android App
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo -e "${{ secrets.ENV_FILE }}" > example/.env
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build Android App
        run: pushd example && flutter build appbundle --release && popd
